services:
  web:
    container_name: web
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tradejournal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    expose:
      - 3000

  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: always
    volumes:
      - ./apps/web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - web
      - api
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./pgdata
      o: bind

